apiVersion: v2
name: kubmeta-lib
description: A KubMeta library Helm chart for Kubernetes
type: application
version: 3.1.11
appVersion: "3.1.11"
home: https://kubmeta.com
icon: https://raw.githubusercontent.com/kubmeta/helm-charts/master/charts/kubmeta-lib/chart-icon.png
sources:
- https://github.com/kubmeta/helm-charts/tree/master/charts/kubmeta-lib
maintainers:
- name: Kubmeta Maintainers
  email: devops@kubmeta.com
keywords:
  - base
  - lib
  - universal
  - nginx
  